// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.3
// source: proto/gitctl.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GitCtl_ListRepositories_FullMethodName = "/gitctl.GitCtl/ListRepositories"
)

// GitCtlClient is the client API for GitCtl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// GitCtl service provides GitHub operations
type GitCtlClient interface {
	// ListRepositories returns all repositories for a given username
	ListRepositories(ctx context.Context, in *ListRepositoriesRequest, opts ...grpc.CallOption) (*ListRepositoriesResponse, error)
}

type gitCtlClient struct {
	cc grpc.ClientConnInterface
}

func NewGitCtlClient(cc grpc.ClientConnInterface) GitCtlClient {
	return &gitCtlClient{cc}
}

func (c *gitCtlClient) ListRepositories(ctx context.Context, in *ListRepositoriesRequest, opts ...grpc.CallOption) (*ListRepositoriesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRepositoriesResponse)
	err := c.cc.Invoke(ctx, GitCtl_ListRepositories_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GitCtlServer is the server API for GitCtl service.
// All implementations must embed UnimplementedGitCtlServer
// for forward compatibility.
//
// GitCtl service provides GitHub operations
type GitCtlServer interface {
	// ListRepositories returns all repositories for a given username
	ListRepositories(context.Context, *ListRepositoriesRequest) (*ListRepositoriesResponse, error)
	mustEmbedUnimplementedGitCtlServer()
}

// UnimplementedGitCtlServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGitCtlServer struct{}

func (UnimplementedGitCtlServer) ListRepositories(context.Context, *ListRepositoriesRequest) (*ListRepositoriesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRepositories not implemented")
}
func (UnimplementedGitCtlServer) mustEmbedUnimplementedGitCtlServer() {}
func (UnimplementedGitCtlServer) testEmbeddedByValue()                {}

// UnsafeGitCtlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GitCtlServer will
// result in compilation errors.
type UnsafeGitCtlServer interface {
	mustEmbedUnimplementedGitCtlServer()
}

func RegisterGitCtlServer(s grpc.ServiceRegistrar, srv GitCtlServer) {
	// If the following call panics, it indicates UnimplementedGitCtlServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GitCtl_ServiceDesc, srv)
}

func _GitCtl_ListRepositories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRepositoriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitCtlServer).ListRepositories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitCtl_ListRepositories_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitCtlServer).ListRepositories(ctx, req.(*ListRepositoriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GitCtl_ServiceDesc is the grpc.ServiceDesc for GitCtl service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GitCtl_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gitctl.GitCtl",
	HandlerType: (*GitCtlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListRepositories",
			Handler:    _GitCtl_ListRepositories_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/gitctl.proto",
}
