// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: proto/gitctl.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ListRepositoriesRequest contains the username to query
type ListRepositoriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRepositoriesRequest) Reset() {
	*x = ListRepositoriesRequest{}
	mi := &file_proto_gitctl_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRepositoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRepositoriesRequest) ProtoMessage() {}

func (x *ListRepositoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gitctl_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRepositoriesRequest.ProtoReflect.Descriptor instead.
func (*ListRepositoriesRequest) Descriptor() ([]byte, []int) {
	return file_proto_gitctl_proto_rawDescGZIP(), []int{0}
}

func (x *ListRepositoriesRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

// ListRepositoriesResponse contains the list of repositories
type ListRepositoriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repositories  []*Repository          `protobuf:"bytes,1,rep,name=repositories,proto3" json:"repositories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRepositoriesResponse) Reset() {
	*x = ListRepositoriesResponse{}
	mi := &file_proto_gitctl_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRepositoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRepositoriesResponse) ProtoMessage() {}

func (x *ListRepositoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gitctl_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRepositoriesResponse.ProtoReflect.Descriptor instead.
func (*ListRepositoriesResponse) Descriptor() ([]byte, []int) {
	return file_proto_gitctl_proto_rawDescGZIP(), []int{1}
}

func (x *ListRepositoriesResponse) GetRepositories() []*Repository {
	if x != nil {
		return x.Repositories
	}
	return nil
}

// Repository represents a GitHub repository
type Repository struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Name            string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	FullName        string                 `protobuf:"bytes,2,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Description     string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	HtmlUrl         string                 `protobuf:"bytes,4,opt,name=html_url,json=htmlUrl,proto3" json:"html_url,omitempty"`
	Private         bool                   `protobuf:"varint,5,opt,name=private,proto3" json:"private,omitempty"`
	Fork            bool                   `protobuf:"varint,6,opt,name=fork,proto3" json:"fork,omitempty"`
	StargazersCount int32                  `protobuf:"varint,7,opt,name=stargazers_count,json=stargazersCount,proto3" json:"stargazers_count,omitempty"`
	ForksCount      int32                  `protobuf:"varint,8,opt,name=forks_count,json=forksCount,proto3" json:"forks_count,omitempty"`
	OpenIssuesCount int32                  `protobuf:"varint,9,opt,name=open_issues_count,json=openIssuesCount,proto3" json:"open_issues_count,omitempty"`
	Language        string                 `protobuf:"bytes,10,opt,name=language,proto3" json:"language,omitempty"`
	CreatedAt       string                 `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       string                 `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	PushedAt        string                 `protobuf:"bytes,13,opt,name=pushed_at,json=pushedAt,proto3" json:"pushed_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Repository) Reset() {
	*x = Repository{}
	mi := &file_proto_gitctl_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Repository) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Repository) ProtoMessage() {}

func (x *Repository) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gitctl_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Repository.ProtoReflect.Descriptor instead.
func (*Repository) Descriptor() ([]byte, []int) {
	return file_proto_gitctl_proto_rawDescGZIP(), []int{2}
}

func (x *Repository) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Repository) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *Repository) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Repository) GetHtmlUrl() string {
	if x != nil {
		return x.HtmlUrl
	}
	return ""
}

func (x *Repository) GetPrivate() bool {
	if x != nil {
		return x.Private
	}
	return false
}

func (x *Repository) GetFork() bool {
	if x != nil {
		return x.Fork
	}
	return false
}

func (x *Repository) GetStargazersCount() int32 {
	if x != nil {
		return x.StargazersCount
	}
	return 0
}

func (x *Repository) GetForksCount() int32 {
	if x != nil {
		return x.ForksCount
	}
	return 0
}

func (x *Repository) GetOpenIssuesCount() int32 {
	if x != nil {
		return x.OpenIssuesCount
	}
	return 0
}

func (x *Repository) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *Repository) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Repository) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Repository) GetPushedAt() string {
	if x != nil {
		return x.PushedAt
	}
	return ""
}

var File_proto_gitctl_proto protoreflect.FileDescriptor

const file_proto_gitctl_proto_rawDesc = "" +
	"\n" +
	"\x12proto/gitctl.proto\x12\x06gitctl\"5\n" +
	"\x17ListRepositoriesRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"R\n" +
	"\x18ListRepositoriesResponse\x126\n" +
	"\frepositories\x18\x01 \x03(\v2\x12.gitctl.RepositoryR\frepositories\"\x97\x03\n" +
	"\n" +
	"Repository\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tfull_name\x18\x02 \x01(\tR\bfullName\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x19\n" +
	"\bhtml_url\x18\x04 \x01(\tR\ahtmlUrl\x12\x18\n" +
	"\aprivate\x18\x05 \x01(\bR\aprivate\x12\x12\n" +
	"\x04fork\x18\x06 \x01(\bR\x04fork\x12)\n" +
	"\x10stargazers_count\x18\a \x01(\x05R\x0fstargazersCount\x12\x1f\n" +
	"\vforks_count\x18\b \x01(\x05R\n" +
	"forksCount\x12*\n" +
	"\x11open_issues_count\x18\t \x01(\x05R\x0fopenIssuesCount\x12\x1a\n" +
	"\blanguage\x18\n" +
	" \x01(\tR\blanguage\x12\x1d\n" +
	"\n" +
	"created_at\x18\v \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\f \x01(\tR\tupdatedAt\x12\x1b\n" +
	"\tpushed_at\x18\r \x01(\tR\bpushedAt2_\n" +
	"\x06GitCtl\x12U\n" +
	"\x10ListRepositories\x12\x1f.gitctl.ListRepositoriesRequest\x1a .gitctl.ListRepositoriesResponseB\"Z github.com/justinsb/gitctl/protob\x06proto3"

var (
	file_proto_gitctl_proto_rawDescOnce sync.Once
	file_proto_gitctl_proto_rawDescData []byte
)

func file_proto_gitctl_proto_rawDescGZIP() []byte {
	file_proto_gitctl_proto_rawDescOnce.Do(func() {
		file_proto_gitctl_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_gitctl_proto_rawDesc), len(file_proto_gitctl_proto_rawDesc)))
	})
	return file_proto_gitctl_proto_rawDescData
}

var file_proto_gitctl_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_gitctl_proto_goTypes = []any{
	(*ListRepositoriesRequest)(nil),  // 0: gitctl.ListRepositoriesRequest
	(*ListRepositoriesResponse)(nil), // 1: gitctl.ListRepositoriesResponse
	(*Repository)(nil),               // 2: gitctl.Repository
}
var file_proto_gitctl_proto_depIdxs = []int32{
	2, // 0: gitctl.ListRepositoriesResponse.repositories:type_name -> gitctl.Repository
	0, // 1: gitctl.GitCtl.ListRepositories:input_type -> gitctl.ListRepositoriesRequest
	1, // 2: gitctl.GitCtl.ListRepositories:output_type -> gitctl.ListRepositoriesResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_gitctl_proto_init() }
func file_proto_gitctl_proto_init() {
	if File_proto_gitctl_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_gitctl_proto_rawDesc), len(file_proto_gitctl_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_gitctl_proto_goTypes,
		DependencyIndexes: file_proto_gitctl_proto_depIdxs,
		MessageInfos:      file_proto_gitctl_proto_msgTypes,
	}.Build()
	File_proto_gitctl_proto = out.File
	file_proto_gitctl_proto_goTypes = nil
	file_proto_gitctl_proto_depIdxs = nil
}
